apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f ./docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: redis-sentinel
  name: redis-sentinel
spec:
  ports:
  - name: "26379"
    port: 26379
    targetPort: 26379
  selector:
    io.kompose.service: redis-sentinel
status:
  loadBalancer: {}
