apiVersion: v1
kind: Service
metadata:
  name: timekeeper-server
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: timekeeper-server

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: timekeeper-server
spec:
  ingressClassName: nginx
  rules:
  - host: localhost
    http:
      paths:
      - path: /timekeeper
        pathType: Prefix
        backend:
          service:
            name: timekeeper-server
            port:
              name: http
